spring:
  application:
    name: quote-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/ez_quote
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  main:
    allow-bean-definition-overriding: true


server:
  port: 8082

application:
  oauth:
    client-id: easy-erp
    client-secret: easy-erp
    client-url: http://oauth.easy-erp.lan/oauth/check_token

security:
  oauth2:
    client:
      clientId: easy-erp
      clientSecret: easy-erp
    resource:
      tokenInfoUri: http://oauth.easy-erp.lan/oauth/check_token
      userInfoUri: http://oauth.easy-erp.lan/api/users/me
      preferTokenInfo: false

easy-erp:
  fileDirectory: /tmp