spring:
  application:
    name: quote-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/ez_quote
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true


server:
  port: 8082

application:
  oauth:
    client-id: easy-erp
    client-secret: easy-erp
    client-url: http://oauth.easy-erp.lan/oauth/check_token
