server:
  port: 8084

spring:
  application:
    name: bill-service

  datasource:
    url: jdbc:mysql://localhost:3306/ez_bill
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none

security:
  oauth2:
    client:
      clientId: easy-erp
      clientSecret: easy-erp
    resource:
      tokenInfoUri: http://oauth.easy-erp.lan/oauth/check_token
      userInfoUri: http://oauth.easy-erp.lan/api/users/me
      preferTokenInfo: false

easy-erp:
  fileDirectory: /tmp
