server:
  port: 8085

spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://localhost:3309/ez_users
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

file:
  uploadDir: /tmp/