server:
  port: 8085

spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://localhost:3309/ez_users
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  mail:
    host: fake-mail-server
    port: 1025
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

