server:
  port: 8081

spring:
  application:
    name: authorization-server
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/oauth_user
    username: root
    password: root
    initialization-mode: always
