spring:
  application:
    name: client-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/ez_quote
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
