spring:
  application:
    name: client-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/ez_client
  jpa:
    hibernate:
      ddl-auto: validate


server:
  port: 8082

application:
  oauth:
    client-id: easy-erp
    client-secret: easy-erp
    client-url: http://localhost:8081