// Generated by https://quicktype.io

export class BillData {
  id?: number;
  createdAt?: Date;
  updatedAt?: Date;
  version?: number;
  status?: string;
  price: number;
  createdBy?: number;
  clientId?: number;
  lines: BillLineData[];
  deleted?: boolean;

  constructor() {
    this.price = 0;
    this.lines = [];
  }
}

export class BillLineData {
  lineNumber: number;
  description: string;
  quantity: number;
  unitaryPrice: number;
  createdAt?: Date;
  updatedAt?: Date;
  version?: number;

  constructor() {
    this.lineNumber = -1;
    this.description = "";
    this.quantity = 0;
    this.unitaryPrice = 0;
  }
}
